apiVersion: v1
kind: Service
metadata:
  name: svc-datanath-frontend-dev
  namespace: app-svc-datanath-frontend-dev
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: 'true'
    service.beta.kubernetes.io/azure-load-balancer-internal-subnet: Subnet-AKS-EC-MAXPOINT
spec:
  type: LoadBalancer
  loadBalancerIP: 10.1.48.220
  selector:
    app: group-app-svc-datanath-frontend-dev
    tier: deployment-svc-datanath-frontend-dev
  ports:
  - name: svc-datanath-frontend-port
    protocol: "TCP"
    port: 4200
    targetPort: 4200